apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      whateverNumber:
        type: number
        default: 2
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - Approval
  Approval:
    needs:
      - build
    with:
      approvers: 85d23c34-a472-11ec-916b-42010a83ae13,random team ,random2
      disallowLaunchByUser: true
      instructions: Random instructions on June 30, 2025
      approvalInputs: |
        {}
    timeout-minutes: 4000
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
