apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      Reviewed:
        type: boolean
        default: false
  schedule:
    - cron: 0 * * 1 *
metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs:
        - job1
    - name: Stage 2
      jobs:
        - job
    - name: Stage 4
      jobs:
        - job3
    - name: Stage 3
      jobs:
        - job2
jobs:
  job1:
    steps:
      - run: echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        name: Hello world
        shell: sh
  job:
    needs: job1
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
  job2:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
    needs: job3
  job3:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "hello world"
    needs: job
